name: searchs_asom
description: The starting point for Dart libraries or applications is Searchs packages
version: 1.0.0
repository: https://github.com/Asomiddin1225/uyishi_91_search_packages/tree/main/packages/searchs
homepage: https://github.com/Asomiddin1225/uyishi_91_search_packages/tree/main/packages/searchs
environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: MIT